apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  googleApiKey: {{ .Values.backend.secrets.googleApiKey | quote }}
  databaseUrl: {{ .Values.backend.secrets.databaseUrl | quote }}
  betterAuthSecret: {{ .Values.backend.secrets.betterAuthSecret | quote }}
  secretKey: {{ .Values.backend.secrets.secretKey | quote }}
